# MOST WIDELY USED ONES ARE CONTENT-BASED AND COLLABERATIVE FILTERING:
# CONTENT-BASED: RECOMMENDATIONS BASED ON SIMILAR FEATURES (FRIDGES AND FRIDGES)
# COLLABERATIVE FILTERING: RECOMMENDATIONS BASED ON COLLECTIVE BEHAVIOUR (A LOT OF PEOPLE BOUGHT THIS TOGETHER WITH THIS, YOU MIGHT AS WELL)
#      CONTENT-BASED: FOCUSES ON CONTENT/USER PREFERENCES
#      COLLABORATE-BASED: FOCUSES ON PEERS WITH SIMILAR TASTE/USER PREFERENCES (MORE POPULAR)
#      MEMORY-BASED: NOT EXPLAINED
#      MODEL-BASED: IDEM

# TO CORRELATE THE ROWS WITHIN ONE DATAFRAME USE .corr(), TO CORRELATE BETWEEN DIFFERENT DATAFRAMES USE .corrwith()
