/*THE PROCESS OF SETTING UP A C-PROGRAM INVOLVES:*/
/*- PREPROCESSING*/
/*- COMPILING*/
/*- ASSEMBLING*/
/*- LINKING*/
/*- LOADING*/
/*PREPROCESSING DOES TEXTUAL SUBSTITION*/
/*THE PREPROCESSOR REMOVES ALL THE COMMENTS*/
/*ALSO, THE PREPROCESSOR INCLUDES ALL FILES THAT ARE NEEDED FOR COMPILATION*/
/*THE PREPROCESSOR ALSO HANDLES EXTENSIONS OF MACROS*/
/*THE PREPROCESSOR COMMANDS ALL BEGIN WITH '#'*/

/*NOTE THAT A CONSTANT CANNOT BE DEFINED TWICE, SO GOOD TO CHECK WHETHER IT ALREADY EXISTS*/
/*CONDITIONAL COMPILATION IS A PORTABILITY TECHNIQUE AND MAKING AN 'IF-ELSE'-CONSTRUCTION FOR THE PREPROCESSOR*/
/*CREATING CONDITIONAL COMPILATION CAN BE DONE WITH: '#if ... [#elif] ... [#else] ... #endif'*/
/*TO CHECK WHETHER SOMETHING (DOESN'T) EXIST(S), USE: '#if defined([NAME]) ... #endif', WHICH CAN BE SHORTENED TO '#ifdef [NAME] ... #endif'; LIKEWISE FOR NOT-EXISTING: '#if !defined([NAME]) ... #endif' AND '#ifndef [NAME] ... #endif'. THIS CAN BE USED TO SEE A VARIABLE IS USED (FOR EXAMPLE: '#define DURK 89998 ... #ifdef DURK [DO SOMETHING] ... #endif*/
/*UNDOING A DEFINITION, USE: '#undef [NAME]'*/
/*THIS GREATLY HELPS WITH DEBUGGING (BEING ABLE TO RUN TEST INDEPENDENTLY OF THE MAIN PROGRAM)*/
/*THEREFORE, IT ALSO HELPS PREVENTING HEADER FILES TWICE (WHICH THROWS AN ERROR)*/

/*THERE ALSO EXISTS '#pragma' (PRAGMATIC INFORMATION) AND '#error'*/
/*THE '#pragma'-DIRECTIVE ALLOWS FOR GIVING COMPILER INSTRUCTIONS IN THE CODE*/
/*THE INSTRUCTIONS THAT CAN BE USED WITH '#pragma' DEPENDS ON THE SPECIFIC COMPILER AND CAN BE FOUND IN THE RESPECTIVE COMPILER'S DOCUMENTATION; AN INSTRUCTION THAT IS NOT RECOGNIZED IS IGNORED*/

#define DURK 12
#ifdef DURK
#pragma message "DUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUURK!"
/*#error What are you thinking, you stupid?*/
#else
    #define DURK 30
#endif


int main( void ){

    return 0;


}
