/*FOUR STAGES FOR CREATING A BINARY ARE:*/
/*- PREPROCESSING (SUBSTITUTION, AMONGST ELSE)*/
/*- COMPILATION (TURNS EVERYTHING IN ASSEMBLY CODE, SYNTAX)*/
/*- ASSEMBLING (CREATES '.o'-FILES)*/
/*- LINKING (GETS EXTERNAL PACKAGES AND CREATES EXECUTABLE FILE)*/
/*SOME OPTIONS ALLOW THE COMPILER TO STOP AT A GIVEN STAGE (FOR EXAMPLE: '-c' ONLY COMPILES, DOES NOT LINK)*/

/*OPTIONS FOR THE COMPILER ARE:*/
/*THE OPTION '-c' ONLY COMPILES BUT DOES NOT LINK (DOES CREATE '.o'-FILES)*/
/*FOR LINKING, USE: '-o [DESIRED NAME EXECUTABLE] [NAME OF THE '.o'-FILES CREATED IN PREVIOUS STEP]'*/
/*TO ENABLE ALL WARNINGS, USE: '-Wall'*/
/*TO LINK TO EXTERNAL LIBRARIES (LIKE 'math.h'), USE: '-l [LIBRARY TO LINK TO]' (FOR EXAMPLE: '-l math')*/
/*FOR EXTRA DEBUGGING-INFORMATION, USE: '-g'*/
/*FOR VERBOSE INFORMATION, USE: '-v'*/
/*OPTIONS CAN ALSO BE PUT IN A FILE AND THEN INVOKED USING: '@[FILENAME]'*/
/*MOST OPTIONS CONSIST OF MULTIPLE LETTERS AS OPTION FOR THE DEBUGGER, SO '-dr' IS SOMETHING ELSE THEN '-d -r'*/
/*THEREFORE, WISE NOT TO GROUP OPTIONS TOGETHER FOR THE COMPILER*/

/*THERE IS ALSO GNU DEBUGGER (gdb) WITH OPTIONS*/
/*GDB CAN START/STOP THE PROGRAM AT ANY POINT WITH ANY SET OF VARIABLES AND PRINT THE STATE AT ANY POINT IT STOPPED*/
/*WHEN THE REGULAR PROGRAM IS COMPILED WITH THE '-g'-FLAG, THE 'gdb'-COMMAND CAN BE INVOKED ON THE EXECUTABLE*/
/*THE COMMAND CAN THEN ACCEPT ALL SORTS OF COMMANDS, LIKE: 'run' (RUNS THE EXECUTABLE, UNTIL IT FINISHES OR CRASHES, WHEN IT CRASHES IT RETURNS AN ANALYSIS); 'list [NUMBER] DISPLAYS 'NUMBER' LINES AROUND THE LAST LINE WHERE THE PROGRAM CRASHED, OR 'list [FUNCTION NAME]' TO PRINT OUT THE BLOCK OF CODE OF THE RESPECTIVE FUNCTION; 'print [VARIABLE]' PRINTS THE LAST VALUE OF A VARIABLE (LAST VALUE CAN BE WHEN PROGRAM CRASHED, VERY USEFUL); 'quit' TO EXIT THE GDB-ENVIRONMENT; 'set var [VARIABLE NAME] = [NEW VARIABLE VALUE]' SETS THE VALUE OF A VARIABLE TO A NEW VALUE*/
/*GDB HAS A NOTION OF CURRENT FILE, CURRENT LINE AND CURRENT FUNCTION*/
/*INSERTING BREAK POINTS IS ALSO POSSIBLE, SO THAT A PROGRAM CAN BE STOPPED AT THAT POINT AND VARIABLES EVALUATED AND CHANGED*/
/*TO SET A BREAKPOINT, USE: 'break [FUNCTION NAME]' OR 'break [LINE NUMBER]'*/
/*AFTER CONTINUING AFTER HITTING A BREAK POINT, USE: 'c' OR 'continue'*/
/*FOR DOING A (SINGLE) STEP AFTER THE BREAK POINT, USE: 's [LINE NUMBER]' OR 'step [LINE NUMBER]' TO EXECUTE THE NEXT 'LINE NUMBER' NEXT LINES AFTER THE BREAK POINT*/
/*TO GET ALL THE (LOCAL) VARIABLES, USE: 'info locals'*/
/*TO GET ALL THE BREAK POINTS, USE: 'info break'*/
/*TO GET RID OF BREAK POINTS, USE: 'clear [FUNCTION]' OR 'clear [LINE NUMBER]'*/
/*WHEN IN OTHER FUNCTIONS (AND BREAKED), IT CAN BE USEFUL TO CALL THE STACK TRACE (BACKTRACKING), WITH: 'backtrack' OR 'bt'*/

/*FOR SOME ERRORS, CORE DUMPS/MEMORY DUMPS/STORAGE DUMPS ARE CREATED, WHICH IN TURN CREATES A CORE FILE WITH USEFUL INFORMATION ON THE ERROR */
/*THOSE CORE FILES ARE PLACED IN THE WORKING DIRECTORY OF THE EXECUTABLE (HAVE THE FORM 'core.[PROCESS NUMBER]'); SOMETIMES THESE CORE FILES ARE DISABLED SINCE THEY CAN BE HUGE*/
/*THESE CORE FILES CAN BE STUDIED WITH GDB*/

/*PROFILING MONITORS THE COMPLEXITY, MEMORY/SPACE, FREQUENCY + DURATION OF FUNCTION CALLS, USAGE OF INSTRUCTIONS*/
/*GPROF IS THE GNU PROFILTER TOOL, WHICH IS NOT THE BEST, VALGRIND IS BETTER TO USE*/

/*STATIC ANALYSIS CATCHES ERRORS BEFORE THE CODE IS COMPILED, DYNAMIC ANALYSIS/PROFILING AFTER COMPILING*/
