/*THERE ARE STANDARD LIBRARIES IN C, LIKE 'math.h' OR 'stdio.h', BUT IT'S ALSO POSSIBLE TO CREATE OWN LIBRARIES*/
/*STATIC LINKING MAKES A COPY OF ALL USED LIBRARY FUNCTIONS TO THE EXECUTABLE FILE (STATIC COMPILE TIME)*/
/*FOR DYNAMIC LINKING, THE LIBRARY FUNCTIONS ARE NOT COPIED, BUT ARE RATHER LINKED DURING RUNTIME (SO BOTH OBJECTS HAVE TO BE PRESENT AT RUNTIME) (DYNAMIC RUNTIME)*/
/*ADVANTAGE OF STATIC LINKING IS SPEED AT RUNTIME, FOR DYNAMIC LINKING THE SPEED AT COMPILE TIME + LESS SPACE OCCUPIED BY BINARY + SAVES VIRTUAL MEMORY (SINCE LIBRARIES ARE ONLY MAPPED WHEN NEEDED) + SAVES SPACE BECAUSE A SINGLE COPY OF THE FUNCTION IS MADE FOR ALL PARTS TO BE USED, INSTEAD OF COPYING THE FUNCTION MULTIPLE TIMES THROUGHOUT THE CODE*/

/*INTERFACE OF STATIC LIBRARIES ARE THE HEADER FILES, SOURCE IS IN '.c'-FILES AND '.o'-FILES TO WHICH ONE SHOULD LINK*/
/*AFTER COMPILATION STATIC LIBRARIES CREATE '.a'-FILES WHICH CAN BE LINKED TO WITH THE '-l'-OPTION (SHORT FOR 'ARCHIVE')*/
/*AFTER COMPILATION FOR DYNAMIC LIBRARIES '.so'-FILES ARE CREATED WHICH HAVE TO BE INCLUDED DURING EXECUTION (SHORT FOR 'SHARED OBJECTS)*/
/*THERE ALSO EXIST 'DYNAMIC LINKED LIBRARY', WHICH REALLY LOADS THE OTHER LIBRARY DYNAMICALLY, WHICH ARE '.dll'-FILES, YET ANOTHER PRINCIPLE*/
/*THERE CAN BE COMPATIBILITY ISSUES WITH DYNAMIC LIBRARIES (NEVER WITH STATIC LIBRARIES), SINCE THE LIBRARY NEEDS TO BE RECOMPILED ONCE THE CODE IS CHANGED, OTHERWISE OLDER VERSIONS ARE BEING USED DURING RUNTIME (+ EXECUTABLE NEEDS TO BE STOPPED)*/

/*AN ARCHIVE-FILE IS A COLLECTION OF '.o'-FILES THAT ARE CREATED AFTER THE LIBRARY SOURCE CODE IS COMPILED*/
/*THE STANDARD LOCATION FOR LIBRARIES IS USUALLY '/usr/local/lib'*/
/*FOR HEADER FILES, IT IS ALWAYS WISE TO INCLUDE AT THE TOP: '#ifndef [VARIABLE NAME SIMILAR TO HEADER FILE NAME] \ #define [VARIABLE NAME SIMILAR TO HEADER FILE NAME] \ [SOME FUNCTIONS THAT ARE DEFINED IN THE HEADER FILE] \ #endif*/
/*OWN LIBRARY FILES ARE INCLUDED IN '"' INSTEAD OF '<'*/
/*FOR CREATING THE LIBRARY, USE: '-c [SOURCE FILE] -o [NAME OF OBJECT FILE].o' AND FOR BUNDLING THE OBJECTS TOGETHER: 'ar rcs [NAME OF ARCHIVE].a [NAME OF OBJECTS].o'*/
/*FOR CHECKING WHAT OBJECT FILES ARE INCLUDED IN THE '.a'-FILE, USE: 'ar -t [ARCHIVE NAME].a'*/
/*FOR INCLUDING THAT OBJECT FOR COMPILING THE FINAL SOURCE CODE, USE: '[SOURCE FILE] [PATH TO + NAME OF OBJECT FILE].o/[PATH TO + NAME OF ARCHIVE].a -o [NAME OF EXECUTABLE]'*/
/*ORDER OF FILES THAT ARE INCLUDED WITH COMPILATION IS VERY IMPORTANT!!!*/

/*TO LIST ALL THE LINKED LIBRARIES FOR AN EXECUTABLE: 'ldd [NAME EXECUTABLE]'*/
/*STANDARD EXTENSION FOR SHARED OBJECT IS '.so'*/
/*FOR CREATING A SHARED OBJECT, USE: '-fPIC [SOURCE FILE] -shared -o [SHARED OBJECT FILE].so', WHERE 'PIC' STANDS FOR POSITION-IDEPENDENT CODE*/
/*THEN FOR EXECUTING, USE '[SOURCE FILE] [PATH TO SHARED OBJECT FILE].so -o [NAME OF EXECUTABLE]', BUT BEWARE THAT YOUR SHARED OBJECT FILE MUST BE IN A DIRECTORY THAT IS INCLUDED IN YOUR $LD LIBRARY PATH ON LINUX*/

/*NORMALLY LINKING IS DONE AT COMPILE TIME (STATIC) OR RUNTIME (DYNAMIC)*/
/*HOWEVER, LOADING CAN ALSO BE DONE STATICALLY OR DYNAMICALLY */
/*LOADING WILL STORE ALL THE REQUIRED LIBRARIES IN MEMORY TOGETHER WITH THE EXECUTABLE AS THE PROGRAM STARTS UP. THIS IS SEPARATE FROM LINKING, WHERE ALL THE LIBRARIES ARE LINKED TOGETHER*/
/*WHEN A LIBRARY IS ONLY LOADED ON-DEMAND DURING RUNTIME, THEN IT IS DYNAMIC LOADING, WHEN IT IS LOADED AT START-UP IT IS CALLED STATIC LOADING (WHICH IS DONE WITH BOTH STATIC AND DYNAMIC LINKING)*/
/*WITH DYNAMIC LOADING THE LOADING AND UNLOADING OF A LIBRARY IS COMPLETELY CONTROLLED BY THE PROGRAMMER*/
/*EXAMPLES THAT USE 'DL'-FILES (DYNAMIC LOADING), SO-FILES ON LINUX, ARE THE PLUGGABLE AUTHENTICATION MODULES (PAM'S) AND INTERPRETERS/COMPILERS*/
/*ADVANTAGE IS THAT THE LIBRARIES CAN INDEPENDENTLY BE UPDATED, SINCE THEY ARE NOT STATICALLY LOADED*/
/*THE LIBRARY 'dlfcn.h' NEEDS TO BE INCLUDED AND WITH: 'dlopen([NAME OF LIBRARY], RTLD_LAZY/RTLD_NOW)' A LIBRARY CAN BE OPENED (DEPENDENCIES MUST BE LOADED FIRST), WHERE SYMBOLS ARE EVALUATED LAZILY OR ACTIVELY NOW, WHICH RETURNS A 'HANDLE'*/
/*FOR LOOKING UP A FUNCTION IN THE GIVEN LIBRARY, USE: 'dlsym([HANDLE],[FUNCTION NAME])'*/
/*FOR CLOSING THE LIBRARY, USE: 'dlclose([HANDLE])'*/
/*TO ENABLE DYNAMIC LOADING, USE THE OPTION '-ldl' WITH COMPILING*/


#include "library.h"
/*#include "dynamiclibrary.h"*/
#include <dlfcn.h>

int main( void ){

    /*FROM THE STATIC LIBRARY*/
    function( );

    /*FROM THE DYNAMIC LIBRARY*/
    /*dynamicfunction( );*/

    /*THIS IS AWESOME!!!*/
    /*DYNAMIC LOADING!!!*/
    void * handle = dlopen( "./dynamiclibrary.so", RTLD_LAZY );
    int ( *dynamicfunction )( void ) = dlsym( handle, "dynamicfunction" );
    ( *dynamicfunction )( );
    dlclose( handle );

    return 0;


}
