/*WITH THE PREPROCESSOR '#define', A SYMBOLIC CONSTANT AND A FUNCTION CAN BE DEFINED; FUNCTIONS DEFINED THIS WAY ARE CALLED MACROS (FOR EXAMPLE: '#define PX(x,y) printf("X IS EQUAL TO %i\n Y IS EQUAL TO %i\n", x, y)')*/
/*MACROS ARE CONSIDERED BAD PROGRAMMING HABIT WITH NEWER PROGRAMMING PRACTICES*/
/*MACROS ARE ON ONE NEWLINE, UNLESS THE BACKSLASH OPERATOR, '\', IS USED FOR CONTINUATION (ON THE NEXT LINE)*/
/*MACROS ARE PREPROCESSED, BUT NOT COMPILED AS FUNCTIONS ARE, WHICH MEANS THAT MACROS ARE MORE PRONE TO ERRORS*/
/*MACROS ARE PREPROCESSED AND PUT IN THE CODE IN INLINE-FASHION, THEREFORE THEY RUN FASTER, BUT COMPILE SLOWER, SINCE THERE IS MORE TEXT TO COMPILE [+ TYPECHECKING IS NOT DONE FOR MACROS, WHICH IS A BIG DISADVANTAGE]*/
/*THE INLINE-ALTERNATIVE IS PREFERRED OVER MACROS SINCE THEY ARE COMPILED AND CHECKED*/
/*SINCE MACROS ARE SUBTITUTED, REALLY TAKE CARE OF PUTTING BRACKETS AROUND THE VARIABLES, SINCE OTHERWISE ORDER OF EXECUTION CAN BE MESSED UP IN THE LITERAL SUBSTITUTION (FOR EXAMPLE: '(5+2)*4' COULD BECOME '5+2*4' WITHOUT BRACKETS)*/
/*VARYADIC MACROS EXIST*/

/*PREPROCESSORS HAVE FOUR OPERATORS THEMSELVES: '\' FOR LINE BREAKS, 'defined([EXPRESSION])' IS FOR CHECKING WHETHER THE EXPRESSION IS ALREADY DEFINED, '#' AND '##' ARE FOR TOKEN CONCATENATION, WHERE '#' CAUSES THE TEXT TO BE REPLACED BY A STRING IN THE CODE AND '##' MENDS TO TOKENS ON EITHER SIDE TO A SINGLE TOKEN*/
/*AN EXAMPLE FOR USING '#' WOULD BE: '#define STRINGCREATION(x) #x'*/
/*AN EXAMPLE FOR USING '##' WOULD BE: '#define CONCAT(x,y) (x) ## (y)'*/

/*PREDEFINED MACROS ARE '__FILE__' (NAME OF CURRENT FILE), '__LINE__' (LINE NUMBER) AND '__func__' (NAME OF FUNCTION WHEN PLACED INSIDE FUNCTION)*/
/*THE NAME AND LINE NUMBER OF A FILE CAN BE USED FOR ERROR MESSAGING FOR WHEN ONE WANTS TO OPEN AND READ/WRITE A FILE*/
/*ALSO '__DATE__' AND '__TIME__' ARE SUPPORTED*/


#include <stdio.h>
#define SUM(x,y) (x)+(y)
#define SQUARE(x) (x)*(x)
#define CUBE(x) (x)*(x)*(x)

int main( void ){

    printf("FILE IS %s, LINE IS %i, LAST COMPILED ON %s, ON THE DAY %s\n", __FILE__, __LINE__, __TIME__, __DATE__);
    printf("SUM IS %e\n", SUM(5.2, 7e3));
    double input = 0;
    printf("GIVE INPUT!!\n");
    scanf("%le", &input);
    printf("SQUARE AND CUBE OF INPUT ARE: %e, %e\n", SQUARE(input), CUBE(input));

    return 0;
}
