/*FOR USING CONSTANTS, USE: '#define [CONSTANT NAME] [CONSTANT VALUE]', WHERE '#' IS A PREPROCESSOR*/
/*NOTICE THAT THERE IS NO EQUAL SIGN AND NO SEMICOLON AT THE END OF THE LINE*/
/*BY CONVENTION, THE CONSTANT NAMES ARE IN UPPERCASE WITH UNDERSCORES (FOR EXAMPLE: 'MURKUMURK_TWO')*/

/*DEFINING TYPES ONESEFL, CAN BE DONE WITH 'typedef', USING: 'typedef [OLD TYPE] [NEW TYPE NAME]' (FOR EXAMPLE: 'typedef int durk', MAKING 'durk' EQUIVALENT TO 'int' FROM THAT MOMENT ONWARD)*/

/*THERE EXISTS VARIABLE-LENGTH ARRAYS, WHERE THE SIZE OF THE ARRAY IS DECLARED IN TERMS OF AN EXPRESSION, RATHER THAN AN HARD-CODED NUMBER*/
/*THIS IS NOT TRIVIAL, C89 DID NOT HAVE IT, NEITHER DID FORTRAN 77*/

/*STRUCTURES CAN HAVE ARRAY MEMBERS THAT DON'T HAVE A PREDEFINED SIZE, THESE ARE REFERRED TO AS 'FLEXIBLE ARRAY MEMBERS'*/
/*HOWEVER, BE AWARE THAT THESE NEED TO BE THE LAST MEMBER OF THE STRUCTURE, AND IT CANNOT BE THE ONLY MEMBER OF THE STRUCTURE*/
/*ALSO, BE AWARE THAT FLEXIBLE ARRAY MEMBERS CANNOT BE USED IN NESTED STRUCTURES*/

/*COMPLEX NUMBERS ARE INTRODUCED IN C11, BUT NOT GENERALLY ACCEPTED*/
/*FOR DECLARATION, USE '_Complex' (FOR FULL COMPLEX NUMBER) AND '_Imaginary' (FOR ONLY IMAGINARY PART); SHORTENED TO 'complex' AND 'imaginary' WHEN 'complex.h' IS INCLUDED (FOR EXAMPLE: 'double complex number = 5 + 6*I')*/

/*THERE ALSO EXISTS DESIGNATED INITIALIZERS, BASICALLY MEANING THAT MEMBERS OF STRUCTURES (AND UNIONS AND ARRAYS) CAN BE INITIALIZED OUT OF ORDER WHEN THE DESIGNATED NAME IS USED (FOR EXAMPLE: 'int array[6] = {[4] = 50, [2] = 7000}', WHICH IS EQUIVALENT TO: 'int array[6] = {[4]50, [2]7000}')*/
/*THIS IS ALSO CONVENIENT FOR INITIALIZING A RANGE USING THE '...'-OPERATOR (FOR EXAMPLE: 'int array[] = {[0 ... 4] = 1, [5] = 80}')*/

/*THERE ARE THREE TYPE QUALIFIERS: 'const', 'volatile' AND 'restrict'*/
/*THESE ARE DIFFERENT THAN THE DATA CLASSIFIERS: 'auto', 'extern', 'static' AND 'register', WHICH IS THE FIRST CLASSIFIER GIVEN IN THE VARIABLE DECLARATION (THESE ARE EXPLAINED IN A DIFFERENT FILE)*/
/*THE 'const'-KEYWORD IS USED FOR CONSTANT WHICH ARE FIXED, HOWEVER, THE DEFINITION IS CHECKED BY THE COMPILER, WHEREAS THE '#define [CONSTANT NAME] [CONSTANT VALUE]' IS NOT CHECKED BY THE COMPILER, SO JUST GIVES A SIMPLE SUBSTITION DURING RUNTIME*/
/*NOTE THAT FOR POINTERS, THE PLACING OF 'const' IS QUITE IMPORTANT: 'const [DATA TYPE] * [POINTER NAME]' MEANS THAT THE VALUE ON THE LOCATION ITSELF CANNOT CHANGE; '[DATA TYPE] * const [POINTER NAME]' MEANS THAT THE PHYSICAL ADDRESS STORED IN THE POINTER CANNOT EVER CHANGE*/
/*AN ADVANTAGE OF USING THE 'const'-KEYWORD IS THAT THIS VARIABLE CAN BE PUT INTO READ-ONLY MEMORY; THE QUALIFIER 'volatile' IS THE OPPOSITE OF 'const' AND IDENTIFIES THAT THE VARIABLE WILL CHANGE ITS VALUE, THIS IS THE DEFAULT IF NOTHING IS SPECIFIED*/
/*USING 'volatile' IS HANDY WHEN RESOURCES ARE SCARCE, SINCE IT PREVENTS CACHING*/
/*AS A LAST QUALIFIER, 'restrict' IS USED TO INDICATE A POINTER, WHICH IS THE SOLE REFERENCE TO THAT MEMORY LOCATION (SO THAT MEMORY IS NOT BEING COVERED BY ANY OTHER POINTER OR VARIABLE); THIS IS HANDY, SINCE THE COMPILER DOES NOT NEED TO CHECK FOR CONSISTENCY OR CASCADING EFFECTS*/
/*WHEN ANOTHER POINTER OR VARIABLE DOES ACCESS THE VALUE IN BETWEEN, THE BEHAVIOUR IS UNDEFINED, SINCE THE COMPILER APPLIED COMPUTATIONAL SHORTCUTS*/
/*THE SYNTAX FOR THIS QUALIFIER IS: '[DATA TYPE] * restrict [POINTER NAME]'*/

#include <complex.h>
#include <stdio.h>

int main (void){

    typedef char * string;

    char durk[] = "DUUUUUUUUUURK!";
    string murk = durk;

    printf("WHATWHATWHAT: %c\n", *(murk + 5));

    int variable_size = 500;
    char big_word[variable_size];

    struct structure {
        char * a_word;
        int flexible_array_member[];
    };

    double complex number = 50 + 500*I;
    printf("MULTIPLYING IMAGINARY NUMBER WITH IT'S CONJUGATE: %e + %ei\n", creal(number*conj(number)), cimag(number*conj(number)));

    static const int durkudurk = 50;
    printf("SHOW THE STATIC CONSTANT: %i\n", durkudurk);

    return 0;


}
