/*SET OF PROPERTIES AND SET OF OPERATIONS DEFINES AN OBJECT/ABSTRACT DATA TYPE ('ADT' SORT OF OBJECT IN C, SIMILAR TO A STRUCTURE)*/
/*EXAMPLES OF ABSTRACT DATA TYPES ARE LISTS, STACKS, QUEUES AND TREES*/

/*LINKED LISTS ARE AN ABSTRACT DATA TYPE. IT IS A LINEAR DATA STRUCTURE, MEANING IT'S COUNTABLE AND IN ORDER, AND IT'S DYNAMIC, MEANING THAT THE SIZE CAN VARY/IS NOT FIXED (ARRAYS ARE STATIC)*/
/*THERE ARE TWO KINDS OF LINKED LISTS: SINGLY-LINKED LISTS CAN ONLY BE TRAVERSED FORWARDLY, DOUBLY-LINKED LIST CAN BE TRAVERSED BOTH WAYS*/
/*LINKED LISTS CAN BE USED WHEN THE SIZE IS UNKNOWN AND DIFFERENT DATA TYPES NEED TO BE COMBINED (ARRAYS ARE STATIC AND CAN ONLY CONTAIN ONE DATA TYPE)*/
/*LINKS/NODES ARE STRUCTURES CONTAINING SOME DATA AND A LINK TO THE NEXT LINK/NODE; LAST LINK/NODE IS SET TO NULL SO THAT IT IS KNOWN WHAT IS THE END; THE FIRST LINK/NODE IS REFERRED TO AS THE HEAD NODE/LINK*/
/*ARRAYS ARE STATIC AND CONTAIN ONLY ONE DATA TYPE, MEMORY IS OFTEN USED INEFFICIENTLY SINCE PART OF THESE ARRAYS CAN BE EMPTY (JUST DECLARED FOR WORST CASE SCENARIO), HOWEVER, LINKED LISTS HAVE MORE OVERHEAD, SO THE ACTUAL MEMORY IS WAY LESS EFFICIENT WITH LINKED LISTS + MORE RISK OF MEMORY LEAKS AND SEGMENTATION FAULTS*/
/*SINCE ARRAYS ARE LOCATED ON THE SAME MEMORY LOCATION, TRAVERSING IS VERY FAST, WHEREAS WITH (LARGE) LINKED LISTS, THE GETTING A SPECIFIC ELEMENT CAN BE SLOW*/

/*STACKS ARE LINKED LISTS WHERE UPDATES ONLY HAPPEN AT THE FIRST ELEMENT OF THE LINKED LIST (THE HEAD)*/
/*IT'S LIFO (LAST IN FIRST-OUT <-> STACK OF PANCAKES), CONTRARY TO QUEUES, WHICH IS FIFO (FIRST ONE IN FIRST ONE OUT <-> SHOP QUEUES)*/
/*MEMORY IS ALSO BUILT UP AS A STACK*/
/*STACKS ARE LINEAR DATA STRUCTURES*/

/*QUEUES ARE LINKED LISTS WHERE INSERTIONS HAPPEN AT THE FIRST ELEMENT (THE HEAD), LIKE A STACK, HOWEVER, DELETIONS ONLY HAPPEN AT THE TAIL*/
/*QUEUES ARE LINEAR DATA STRUCTURES*/

/*TREES ARE THE ONLY NON-LINEAR DATA STRUCTURE IN THIS FILE*/
/*ROOT NODE IS THE TOP OF THE TREE; CHILDREN OF A NODE ARE SIBLINGS AND A NODE WITHOUT SIBLINGS IS A LEAF NODE*/
/*TREES CONSIST OF LAYERS*/

/*DIFFERENCES BETWEEN LINKED LISTS, STACKS, QUEUES AND TREES ARE MAINLY THERE METHODS*/


#include <stdio.h>
#include <stdlib.h>

/*LINKED LIST DEFINITIONS:*/
typedef struct node {
    double data;
    struct node * next_node;
    /*struct node * previous_mode;*/
} node_example;

typedef node_example * list_nodes;

int main( void ){



    return 0;


}
