/*MOST NETWORKING IS DONE WITH C AS THE BASE LANGUAGE*/
/*MOST NETWORKS WORK WITH SERVERS AND CLIENTS; INDEPENDENT PROGRAMS CAN BE SET UP TO BE A SERVER-PROGRAM AND/OR A CLIENT-PROGRAM*/
/*TRANSMISSION CONTROL PROTOCOL (TCP) MAKES USE OF THE INTERNET PROTOCOL (IP) TO DEFINE HOW PACKETS ARE SENT BETWEEN PROGRAMS*/
/*THE WORLD WIDE WEB, EMAIL, REMOTE ADMINISTRATION AND FILE TRANSFER USE THE TRANSMISSION CONTROL PROTOCOL*/
/*TCP IS A CONNECTION-ORIENTED PROTOCOL, MEANING THAT FOR THE TRANSFER TO TAKE PLACE, THE CONNECTION NEEDS TO BE MAINTAINED*/
/*WITH TCP, DUPLICATES ARE HANDLED, LOST PACKETS ARE RESTORED, ORDER CAN BE IMPLEMENTED, FLOW CAN BE BOTH WAYS (FULL DUPLEX), IT IS RELIABLE AND HANDLES PACKET JAMS*/

/*ONE PROGRAM (CLIENT) CAN REQUEST INFORMATION FROM ANOTHER PROGRAM (SERVER); ONE SERVER CAN SERVE MULTIPLE CLIENTS*/
/*COMMUNICATION BETWEEN CLIENTS AND SERVERS USE TCP*/
/*THE CONNECTION IS MADE OVER THE LOCAL AREA NETWORK (LAN) OR WIDE AREA NETWORK (WAN ~ WORLD WIDE WEB)*/
/*CLIENTS NEED TO KNOW THE ADDRESS OF THE SERVER, BUT NOT THE OTHER WAY AROUND*/
/*SINCE MULTIPLE CLIENT CAN BE ATTACHED TO A SINGLE SERVER, SPECIAL PROGRAMS CALLED DAEMONS CAN BE USED TO HANDLE THE REQUESTS AND ESTABLISH THE CONNECTIONS*/

/*THERE ARE TWO TYPES OF SERVERS: ITERATIVE (WHERE REQUESTS QUEUE UP) AND CONCURRENT (MULTIPLE REQUESTS CAN BE HANDLED SIMULTANEOUSLY)*/

/*SOCKETS ARE VIRTUAL ENDPOINTS IN THE TCP-PROTOCOL/CONNECTION BETWEEN NODES*/
/*THE SERVER SOCKET LISTENS TO A PARTICULAR PORT AT AN ADDRESS; ANOTHER SOCKET CONNECTS TO THAT ADDRESS+PORT*/
/*STEPS FOR THE SERVER ARE: CREATION OF SOCKET, ATTACH ADDRESS TO SOCKET (BIND THE SOCKET), ANNOUNCE AVAILABILITY (LISTENING ON THE PORT), RECEIVING CONNECTIONS, ACCEPTING CONNECTIONS, EXCHANGE PACKETS AND FINALLY CLOSE/RELEASE THE CONNECTION*/

/*DIFFERENT LIBRARIES FOR SOCKETS ARE: 'sys/types.h', 'sys/socket.h', 'netinet/in.h', 'netdb.h' AND 'arpa/inet.h'*/
/*DIFFERENT SERVER PROGRAMS USE DIFFERENT PORTS TO NOT MIX UP THE SERVICE PROVIDED*/
/*A PORT SMALLER THAN 1024 IS A SYSTEM/RESERVED PORT, THE REST CAN BE USED FOR OTHER APPLICATIONS*/
