/*SCANF AND PRINTF MOST FAMOUS EXAMPLES OF INPUT/OUTPUT (I/O)*/
/*ALL RELATED FUNCTIONS ARE IN THE 'stdio.h' LIBRARY*/
/*ALL THESE FUNCTIONS ARE BASED ON STANDARD INPUT, STANDARD OUTPUT AND STANDARD ERROR*/
/*BECAUSE OF THIS, 'stdin' IS A KEYWORD THAT CAN ACTUALLY BE USED IN FUNCTIONS, LIKE 'stdout' AND 'stderr'; 'stdin' IS NORMALLY STANDARD INPUT THAT IS READ FROM THE TERMINAL, BUT CAN ALSO BE A FILE, SINCE THIS IS ALSO BE MADE STANDARD INPUT*/

/*FUNCTIONS FOR CHARACTERS INCLUDE: 'getc' (READS IN FROM THE STANDARD INPUT, CAN BE TERMINAL CAN BE FILE); 'getchar' (ONLY READS IN FROM THE TERMINAL); 'fgetc' (READS IN FROM THE STANDARD INPUT, BOTH TERMINAL OR FILE); 'ungetc' (READS IN FROM STANDARD INPUT, BUT CAN BE USED TO RE-READ CHARACTER FROM A FILE THAT IS JUST READ WITH 'getc'); 'putc' (WRITING SINGLE CHARACTER TO STANDARD OUTPUT, CAN BE TERMINAL OR FILE); 'putchar' (ONLY WRITES A SINGLE CHARACTER TO THE TERMINAL); 'fputc' (WRITES SINGLE CHARACTER TO FILE, INCREASING THE POINTER ONE POSITION)*/
/*FUNCTIONS FOR STRINGS INLCUDE: 'fgets' (READS IN A WHOLE LINE OF THE STANDARD INPUT OR A SPECIFIED NUMBER OF CHARACTERS, CAN BE TERMINAL INPUT OR FILE); 'getline' (SAME AS 'fgets', ONLY MORE RELIABLE); 'puts' (WRITES A WHOLE LINE TO STANDARD OUTPUT, CAN ONLY BE TERMINAL, DOES NOT ALLOW FOR SPECIFIERS, SO THE LINE IS A CONSTANT); 'fputs' (WRITES A WHOLE LINE TO STANDARD OUTPUT, CAN BE FILE AND TERMINAL, DOES NOT ALLOW FOR SPECIFIERS)*/
/*FUNCTIONS FOR FORMATTING INCLUDE: 'sprintf' (WRITES FORMATTED OUTPUT TO A STRING, SIMILAR TO 'printf', BUT WRITING TO STRING/BUFFER, BUT CAN CAUSE BUFFER OVERFLOW BECAUSE OF THIS); 'fprintf' (WRITES FORMATTED OUTPUT TO A FILE OR TO STANDARD ERROR, WHICH IS VERY USEFUL); 'fscanf' (READS INPUT FROM A FILE, SIMILAR TO 'scanf', BUT THEN FROM A FILE); 'sscanf' (READS FORMATTED INPUT FROM A STRING, SIMILAR TO SCANF, BUT FROM A STRING)*/


#include <stdio.h>

int main( void ){

    int input = 0;
    int countwords = 1, countcharacters = 0;
    FILE *stream;

    stream = fopen( "basic bits.c", "rw" );
    if( stream == 0 ){ printf("CAN'T OPEN NOOOOOOOOOO\n"); };

    /*while ( ( input = getc( stream ) ) != EOF ){*/
    while ( ( input = getc( stdin ) ) != EOF ){
        /*printf( "%c", input );*/
        
        countcharacters++;
        if ( input == ' ' || input == '\n' ){
            countwords++;
        }
    }

    printf( "THE NUMBER OF CHARACTERS IS: %i, THE NUMBER OF WORDS IS: %i\n", countcharacters, countwords );

    fclose( stream );

    return 0;


}
