/*C HAS VERY CONVENIENT LIBRARIES BUILT IN*/

/*THERE IS A LIBRARY CALLED 'assert.h' WHICH ENABLES TO MAKE RUNTIME DEBUGGING TESTS*/
/*THE FUNCTION 'assert([RELATIONAL OR LOGICAL EXPRESSION])' ABORTS THE PROGRAM WHEN 'FALSE' IS RETURNED FROM THE ARGUMENT EXPRESSION (SEE 'abort' BELOW)*/
/*THE FUNCTION RETURNS THE LINE WHERE THE ERROR OCCURED AND SOME ERROR MESSAGE TO stderr*/
/*ONLY USE FOR CRITICAL TEST, DON'T SUBSTITUTE REGULAR TESTING WITH THIS*/
/*TO SWITCH OF ALL ASSERTIONS, DEFINE 'NDEBUG' AT THE BEGINNING OF THE CODE (BEFORE 'assert.h' IS INCLUDED)*/

/*A LOT OF FUNCTIONS ARE INCLUDED IN 'stdlib.h'*/
/*THIS LIBRARY INCLUDES RANDOM NUMBER GENERATION, PROGRAM TERMINATION FUNCTIONS (LIKE 'exit()' OR 'abort()'), SEARCHING AND SORTING FUNCTIONS, TYPECASTING/CONVERSION FUNCTIONS, MEMORY-MANAGEMENT FUNCTIONS*/
/*THE 'exit([EXIT-STATUS, AN INTEGER])'-FUNCTION REALLY TERMINATES PRELIMINARY WHEN A FATAL ERROR OCCURED*/
/*THE 'abort()'-FUNCTION IS EVEN MORE DRASTIC AND DUMPS CORE IMMEDIATELY AND CREATES A 'SIGABRT'-SIGNAL; REALLY TERMINATES DRASTICALLY AND HARD*/
/*FOR RANDOM NUMBER GENERATION THERE IS THE 'rand()'- AND 'srand'-FUNCTION, WHERE 'rand()' TAKES NO ARGUMENTS AND RETURNS A NUMBER BETWEEN 0 AND 'RAND_MAX', WHEREAS 'srand' CAN TAKE A SEED AS AN ARGUMENT (NO SPECIFIC ARGUMENT DEAULTS TO 1)*/
/*FOR CONVERSION THERE ARE THE FOLLOWING FUNCTIONS: 'atoi([CHARACTER ARRAY])', 'atof([CHARACTER ARRAY])', 'atol([CHARACTER ARRAY])', 'strtod([STRING])', 'strtof([STRING])', 'strtol([STRING])' AND 'itoa([INTEGER])', WHERE 'a' STANDS FOR ASCII*/
/*FOR GETTING ENVIRONMENT VARIABLES OF THE EMBEDDING SYSTEM, USE: 'getenv'*/
/*FOR INTERACTING WITH THE EMBEDDING SYSTEM, USE: 'system()', ALLOWS FOR EXECUTING COMMAND IN THE OVERARCHING SHELL (FOR EXAMPLE: 'system(history | grep q)')*/


#define NDEBUG
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

int main( void ){

    assert( 5 == 4 );
    printf( "ASSERT NOT EXECUTED\n" );
    
    system( "history | grep q" );
    system( "ls" );

    for( int i = 0; i < 50; i++, printf( "%e ", ( double ) rand( )/RAND_MAX ) );
    printf( "\n" );

    printf( "PATH ENVIRONMENT %s\n", getenv( "PATH" ) );
    
    return 0;


}
