# TRY, ELSE, EXCEPT [TYPE OF ERROR, NOT MANDATORY], FINALLY
# TRY: ATTEMPT THIS (ERROR MAY OCCUR)
# ELSE IN CASE NO ERROR OCCURRED, NOT NECESSARY (CAN PUT ALL CODE IN TRY-BLOCK)
# EXCEPT [TYPE OF ERROR, NOT MANDATORY]: DO THIS, IN CASE TRY-CODE GIVES RISE TO AN ERROR
# A FINAL BLOCK OF CODE, TO BE EXECUTED REGARDLESS OF ERRORS IN THE TRY-CODE

# unittest BUILT-IN LIBRARY THAT TESTS YOUR CODE
# pylint IMPORTED LIBRARY, TESTS AUTOMATICALLY FOR YOU + SOME BASIC STATISTICS