# MAP, FILTER AND LAMBDA EXPRESSIONS

def square(num):
    return num**4

number_list = [4,321,25,45,14,13,33531,1,3]

# MAP TAKES IN A FUNCTION AND THEN A ITERABLE OBJECT
print(list(map(square,number_list)))

# FILTER TAKES A FUNCTION THAT RETURNS EITHER TRUE OR FALSE, PASSES AN ITERABLE AND GIVES BACK THE ARGUMENTS THAT RETURN TRUE
def domdomdom(num):
    return num%(int(num/2)+1)

print(list(filter(domdomdom,number_list)))

# LAMBDA EXPRESSIONS ARE FUNCTIONS THAT YOU DON'T NEED TO SAVE IN MEMORY, JUST LOCALLY

print(list(map(lambda num: num**9, number_list)))

# LEGB RULE: LOCAL FIRST, THEN ENCLOSING FUNCTION, THEN GLOBAL VARIABLES (NO INTENDATION) AND LAST BUILT-IN PYTHON FUNCTIONS