# IN ORDER TO MAKE YOUR OWN MODULES AND PACKAGES, PUT AN __init__.py FILE IN A DIRECTORY
# SYNTAX: FROM NAMEDIRECTORY IMPORT FILE, OR: FROM NAMEDIRECTORY/FILENAME IMPORT FUNCTION
# IN CASE OF SUBDIRECTORY SYNTAX IS NAMEDIRECTORY.SUBDIRECTORY

from oop import Classy

cliff = Classy(True)
cliff.sassy("AND BEAUTIFUL")
