// MODEL-VIEW-CONTROLLER MODEL:
// MODEL: CALCULATIONS
// VIEW: HANDLES HTTP-REQUEST
// CONTROLLER: MANAGING THOSE TWO PARTS. ALSO CONTAINS THE STATE OF THE SYSTEM (CURRENT SEARCH, CURRENT SHOPPING CART, ETC.) AND EVENTLISTENERS