#MACHINE LEARNING IS A SUBFIELD OF COMPUTER SCIENCE THAT GIVES COMPUTERS THE ABILITY TO LEARN WITHOUT BEING EXPLICITLY PROGRAMMED
#MACHINE LEARNING IS FIT FOR OBJECT RECOGNITION, SUMMARIZATION AND RECOMMENDATIO
#REGRESSION (CONTINUOUS VERSUS CONTINUOUS), CLASSIFICATION (DISCRETE VERSUS CONTINUOUS), CLUSTERING (UNSUPERVISED, GROUPING DATA), ASSCOCIATION (FEATURE GROUPING); APPLICATIONS: ANOMALY DETECTION, SEQUENCE MINING (PREDICTING NEXT EVENT, HIDDEN MARKOV MODELS), DIMENSION REDUCTION, RECOMMENDATION SYSTEMS
#MACHINE LEARNING IS THE STATICAL PART OF ARTIFICIAL INTELLIGENCE, DEEP LEARNING A SPECIFIC, NONLINEAR EXAMPLE OF MACHINE LEARNING
#SUPERVISED: ANSWER KNOWN BEFOREHAND (CLASSIFICATION AND REGRESSION); UNSUPERVISED: NO ANSWER KNOWN BEFOREHAND (CLUSTERING, DIMENSIONALITY REDUCTION, DENSITY ESTIMATION, MARKET BASKET ANALYSIS)
#ATTRIBUTES (NAMES/CATEGORIES) + DATA = FEATURES; ANSWER = CLASS; ROW OF TABLE = SINGLE OBSERVATION
#DATA TYPES: NUMERICAL AND CATEGORICAL
