/* QUERY PERFORMS A RADICAL TRANSACTION THAT IS ROLLED BACK */

/* TRANSACTIONS ARE MAINLY FOR DATA INTEGRITY */
/* TRANSACTIONS ARE ACID-COMPLIANT: ATOMIC ("ALL OR NOTHING"), CONSISTENT (ONLY SUCCESS CHANGES 
    STATE), ISOLATED (INDEPENDENT FROM OTHER TRANSACTIONS), DURABLE (PERSIST EVEN AFTER SYSTEM 
    FAILES AFTERWARDS -- ARE NOT ROLLED BACK THEN) */
/* TRANSACTIONS' SYNTAX IS: BEGIN - COMMIT/END OR ROLLBACK (WHICH CANCELS THE TRANSACTION */
/* NOTE THAT TRANSACTIONS WITH ERRORS WILL BE ROLLED BACK COMPLETELY, EVEN WITH A COMMIT/END-KEYWORD */
/* FURTHERMORE, SAVEPOINTS CAN BE INTRODUCED, WHICH ALLOWS ONE TO ROLL BACK TO SPECIFIC POINTS WITHIN
THE TRANSACTION */
/* TABLES ARE LOCKED IN TRANSACTIONS IF THEY ARE FIDDLED WITH -- CAN BE DONE EXPLICITLY WITH 
'LOCK TABLE table_name (lock-mode)'-COMMAND */

BEGIN;

    SELECT NOW();
    /* NOTE THAT CASCADE NEEDS TO BE USED HERE, SINCE OTHER TABLES CONTAIN REFERENCES TO THESE ONES */
    DROP TABLE general_hospital.accounts CASCADE;
    /* A SAVEPOINT IS CREATED AFTER THE FIRST DROP */
    SAVEPOINT durk;
    DROP TABLE general_hospital.physicians CASCADE;
    /* NOTE THE TIME DIDN'T CHANGE, THE TIME OF THE START OF THE TRANSACTION IS USED HERE */
    SELECT NOW();
    /* A RETURN TO THE SAVEPOINT IS DONE HERE, SO EVERYTHING AFTER THE SAVEPOINT IS ROLLED BACK */
    ROLLBACK TO durk;

    
ROLLBACK;

/* TO DEMONSTRATE NOTHING IS LOST */
SELECT *
FROM general_hospital.accounts
LIMIT 2
;
