/*OPERATORS ARE INFIX IS C, LIKE IN MOST LANGUAGES (CONTRARY TO PREFIX OR POSTFIX OPERATORS)*/
/*OPERATOR IS THE 'SYNMBOL', THE OPERANDS ARE THE ARGUMENTS TO THAT SYMBOL*/
/*THERE IS A DIFFERENCE BETWEEN LOGICAL AND ARITHMETIC OPERATORS, AND RELATIONAL AND BITWISE OPERATORS*/
/*AN EXPRESSION CONSISTS OF A COMBINATION OF OPERATORS AND OPERANDS, SO EVERY EXPRESION HAS A VALUE*/
/*STATEMENTS ARE A COMBINATION OF EXPRESSIONS, A COMPLETE INSTRUCTION TO THE COMPUTER (DECLARATION STATEMENT OR ASSIGNMENT STATEMENT OR FUNCTION CALL STATEMENT OR STRUCTURE STATEMENT (LOOPS) OR RETURN STATEMENTS)*/
/*COMPOUND STATEMENTS/BLOCKS IS A COLLECTION OF STATEMENTS BETWEEN CURLY BRACES (FOR EXAMPLE IN FUNCTIONS)*/

/*OPERATORS:*/
/*- ARITHMETIC: +,-,*,%,/,++,-- (LAST ONE ARE INCREMENT AND DECREMENT BY ONE) */
/*- LOGICAL: &&,||,! */
/*- ASSIGNMENT:=,*=,+=,-=,/=,%= (FOR EXAMPLE: 'a-=b' IS THE SAME AS 'a = a - b'), OTHER ASSIGNMENT OPERATORS ARE <<= (LEFT SHIFT + ASSIGNMENT), >>=, &= (BITWISE AND + ASSIGNMENT), ^= (BITWISE EXCLUSIVE OR + ASSIGNMENT), |= (BITWISE INCLUSIVE OR + ASSIGNMENT)*/
/*- RELATIONAL:==,<=,>=,<,>,!=*/
/*- BITWISE:OPERATE ON BITS, IN INTEGER VALUES, EXAMPLES ARE BITWISE AND '&', BITWISE OR '|', BITWISE EXCLUSIVE OR '^', BINARY INVERSION '~', BINARY LEFT SHIFT OPERATOR '<<', BINARY RIGHT SHIFT OPERATOR '>>'*/
/*BITWISE OPERATORS HAVE THE EFFECT OF COMPARING TWO NUMBERS BIT-WISE (0011 & 0110 = 0010, 0011 | 0110 = 0111, 0011 ^ 0110 = 0101, ~0011 = 1100, 0011 >> 1 = 1001, 0011 << 2 = 1100)*/
/*BE AWARE THAT THERE IS A DIFFERENCE BETWEEN 'a++' AND '++a', WHERE WITH THE FIRST ONE, 1 IS ADDED AFTER THE STATEMENT IS EVALUATED, WITH THE SECOND ONE, 1 IS ADDED BEFORE THE STATEMENT IS EVALUATED */
/*CAST AND SIZEOF ARE ACTUALLY OPERATORS, WHILE LOOKING LIKE FUNCTIONS; CASE DOES TYPE CONVERSION (FOR EXAMPLE: '(float) 5/3'), SIZEOF DETERMINES SIZE IN BITS OF VARIABLES OR DATA TYPES (FOR EXAMPLE: 'sizeof(int)')*/
/*THERE IS ANOTHER OPERATOR FOR DEREFERENCING A POINTER, WHICH IS: '*[POINTER]'*/

#include <stdio.h>
int main(void)
{
    printf("DURK %lu\n", sizeof(int));
    printf("DURK %lu\n", sizeof(double));
    printf("DURK %lu\n", sizeof(long));
    printf("DURK %lu\n", sizeof(char));
    printf("DURK %lu\n", sizeof(_Bool));
    printf("DURK %lu\n", sizeof(unsigned int));
    int minutes;
    scanf("%i", minutes);
    printf("MINUTES %i\n", minutes);
    printf("THIS IS %e DAYS AND %e YEARS\n", ((double) minutes)/(60*24), ((double) minutes)/(60*24*365));
    return 0;
}
