/*COMMON PROBLEMS ARE:*/
/*- LOGIC*/
/*- SYNTAX*/
/*- MEMORY CORRUPTION (ESPECIALLY IN C)*/
/*- PERFORMANCE*/
/*- LACK OF COHESION*/
/*- OVERCOUPLING MODULES*/
/*TRY TO REPRODUCE ERRORS WHEN ONE OCCURS*/

/*C DOES NOT HAVE EXCEPTION HANDLING (TRY-CATCH BLOCKS)*/

/*A STACK TRACE/CALL STACK IS GENERATED AFTER A FATAL ERROR*/
/*A CALL STACK SHOW THE FUNCTIONS THAT LEAD TO THE ERROR (TOP SHOWS THE MOST RECENT CALL, BOTTOM MOST DISTANT CALL)*/

/*THERE IS A DIFFERENCE BETWEEN VARIABLES AND POINTERS, AND THIS IS OFTEN A SOURCE OF ERRORS (FOR EXAMPLE: '.' IS FOR STRUCT VARIABLES AND '->' IS FOR STRUCT POINTERS)*/
/*IF THERE ARE MORE ERRORS FLAGGED BY THE COMPILER, ALWAYS FIX THE FIRST ONE FIRST, SINCE THE OTHER ERRORS MIGHT BE CAUSED BY THE FIRST ERROR*/
