/*ON A COMPUTER PROGRAMS ARE THE BRIDGE BETWEEN USER AND MACHINE*/
/*ONE A SLIGHTLY LOWER LEVEL, COMPUTERS CONTAIN AN INSTRUCTION SET, WHICH ARE THE BINARIES THAT COMMUNICATE WITH THE HARDWARE*/
/*A PROGRAM SENDS INSTRUCTIONS TO THE INSTRUCTION SET*/
/*THIS CAN BE DONE IN ANY PROGRAMMING LANGUAGE*/

/*CPU IS THE CENTRAL PROCESSING UNIT, WHERE INSTRUCTIONS ARE EXECUTED*/
/*RAM IS RANDOM ACCESS MEMORY, WHERE DYNAMIC MEMORY RESIDES*/
/*HARD DRIVE IS WHERE THE PERMANENT MEMORY RESIDES*/

/*FETCHING/EXECUTION CYCLE: THE CPU FETCHES THE INSTRUCTION FROM MEMORY AND THEN EXECUTES IT*/
/*A GIGAHERTZ CPU DOES THIS A BILLION TIME PER SECOND*/
/*THE DATA IS FETCHED FROM EITHER RAM OR LOCAL REGISTERS, THEN DECODED/EXECUTED BY THE CONTROL UNIT AND THEN EXECUTED BY THE ALU, AND THE RESULT IS STORED IN RAM OR REGISTERS AGAIN*/

/*HIGHER LEVEL PROGRAMMING LANGUAGES ARE MACHINE-AGNOSTIC, LANGUAGES SUCH AS C*/
/*THIS IS CONTRARY TO ASSEMBLY, WHICH IS DEPENDENT ON HARDWARE*/
/*THE COMPILER/TRANSLATOR CONVERTS THE HIGHER LEVEL LANGUAGE TO ASSEMBLY LANGUAGE AND/OR INSTRUCTIONS, CALLED THE EXECUTABLE*/
/*COMPILERS ALSO CHECK FOR SYNTAX, SO A GOOD COMPILER DOES NOT PRODUCE AN EXECUTABLE OF THE SYNTAX IS INCORRECT*/

/*C IS AN IMPERATIVE (NEXT TO DECLARATIVE, FUNCTIONAL OR LOGIC), GENERAL-PURPOSE (HIGH-LEVEL) PROGRAMMING LANGUAGE*/
/*ITS STATEMENTS CHANGE THE PROGRAMS STATE*/
/*ORGANIZED AROUND FUNCTIONS (ENHANCING MODULAR DESIGN) AND STRUCTURE*/

/*DRIVERS ARE PROGRAMS THAT INTERACT WITH HARDWARE, THE MAJORITY IS WRITTEN IN C*/
/*THE LINUX KERNEL IS WRITTEN IN C*/

/*FOR WRITING A C PROGRAM OR A PROGRAM IN ANY COMPILED LANGUAGE: EDIT, COMPILE, LINK (GETTING ALL THE EXTERNAL LIBRARIES INTO AN EXECUTABLE/OBJECT AS WELL, LINKING IS THEN COLLECTING ALL THESE EXECUTABLES TOGETHER; IT TAKES ALL THESE OBJECT FILES AND CREATES ONE, SINGLE EXECUTABLE), EXECUTE*/
/*COMPILING HAPPENS IN TWO STAGES: PREPROCESSING (THERE CAN STILL SOMETHING BE ADDED TO THE CODE) AND TRANSLATING TO INSTRUCTIONS/ASSEMBLY*/
/*COMPILERS DO NOT FIND LOGICAL ERRORS*/
/*THE COMPILER CREATES AN EXECUTABLE, THIS IS SOMETIMES CALLED AN OBJECT AND THESE EXECUTABLE FILES HAVE THE EXTENSION '.o' (E.G.: 'durk.o')*/
/*THE TWO COMPILERS ARE 'gcc' OR 'cc', USE THE FLAG '-o' BEFORE THE EXECUTABLE NAME (E.G.: 'gcc durk.c -o durk')*/
/*LINKING ALSO HAS TWO PHASES */
/*A REFERENCE TO AN EXTERNAL OBJECT THAT DOES NOT EXIST GIVES A LINKING ERROR*/
/*EXTERNAL LIBRARIES ARE CALLED PROGRAM LIBRARIES*/

/*SINCE 'main' HAS BRACKETS AFTER IT, IT SIGNIFIES THAT 'main' IS A FUNCTION*/
/*THE 'main'-FUNCTION IS THE ENTRY-POINT TO THE PROGRAMS*/
/*THE '{' AND '}' SIGNIFY A BLOCK OF CODE (ESPECIALLY THE CODE THAT WILL BE EXECUTED WHEN A FUNCTION IS RUN, HERE 'main')*/
/*ALL STATEMENTS NEED THE END WITH AN ';'*/
/*THE 'int' BEFORE 'main' SIGNIFIES THAT THE FUNCTION IS GOING TO RETURN AN INTEGER (CAN BE 'void' OR 'float' AS WELL)*/
/*THE 'void' WITHIN THE 'main'-BRACKETS SIGNIFY THAT THE 'main'-FUNCTION ONLY ACCEPTS 'void' ARGUMENTS (NO ARGUMENTS)*/
/*SINCE 'main' IS A RESERVED KEYWORD, VARIABLES CAN'T BE CALLED 'main'*/

/*EXAMPLE*/
#include<stdio.h>
int main(void)
{
 printf("Hello World!\n");
 return 0;
}
