/*MEMORY IS STORED IN RAM (WHICH IS DISPOSED AFTER CLOSING) AND HARD-DRIVE, WHICH PERSISTS*/
/*VARIABLES ARE STORED IN RAM*/
/*CONSTANTS RETAIN THEIR VALUE THROUGHOUT THE LIFETIME OF A PROGRAM*/
/*VARIABLES CAN HAVE DIFFERENT VALUES THOUGHOUT THE LIFETIME OF A PROGRAM*/
/*NAMES ARE GIVEN TO VARIABLES AND CONSTANTS, IN ORDER TO MAKE THE SEARCH FOR THEM EASIER THEN BY SOLELY THEIR MEMORY ADDRESSES*/
/*IN C ALL NAMES MUST START WITH EITHER A LETTER OR A '_' AND THEN ANY ALPHANUMERIC COMBINATION CAN FOLLOW*/
/*EXAMPLES OF DATA TYPES ARE INT, FLOAT, DOUBLES, CHAR AND OTHERS*/
/*DECLARING VARIABLES IS DONE WITH 'DATA TYPE , NAME' (FOR EXAMPLE: 'int durk' OR 'double durk_one, durk_two, durk_three')*/
/*ASIGNING A VALUE TO A VARIABLE IS DONE WITH '=' (FOR EXAMPLE: 'durk = 9000' OR 'double durk = 90.02'); INITIALIZATION IS THE FIRST DECLARATION FOR A VARIABLE OR CONSTANT*/

/*THE DIFFERENCE BETWEEN DATA TYPES IS THE AMOUNT OF MEMORY THAT IS ALLOCATED FOR THEM*/
/*EXAMPLES OF DATA TYPES ARE: INT (IF PRECEDED BY 0x THEN IT IS READ IN HEXADECIMAL [BASE 16], FOR EXAMPLE: 'int durk = 0x14'), FLOAT (CAN BE EXPRESSED IN SCIENTIFIC NOTATION, FOR EXAMPLE: 'float durk = 3e45'), DOUBLE (LARGER THAN FLOAT), _BOOL (ACTUALLY WRITTEN AS '_Bool'), CHAR  */
/*FOR BOOLEAN: WHEN 'stdbool.h' IS INCLUDED, THE 'bool' DATA TYPE CAN BE USED, WHICH ACCEPTS 'true' OR '1', AS EXAMPLES*/
/*FOR NUMERICAL VALUES, ONE CAN ALSO INCLUDE 'short', 'long', 'long long' AND 'unsigned' BEFORE IT TO REDUCE THE AMOUNT OF MEMORY USED (FOR EXAMPLE: 'unsigned int durk')*/
/*ENUM ALLOWS THE SPECIFICATION OF ONE'S OWN VARIABLES, WITH THE SYNTAX 'enum name {valid values}' (FOR EXAMPLE: 'enum primary_color {red, yellow, blue}')*/
/*INITIALIZATION FOR ENUMS GOES WITH 'enum [ENUM_TYPE] [VARIABLE_NAME]' (FOR EXAMPLE: 'enum primary_color durk = red', REFERENCING PREVIOUS LINE)*/
/*UNDER THE HOOD ENUMS ARE DEFINED AS INTEGERS, MEANING THAT IN THE PREVIOUS EXAMPLE 'durk' WOULD BE EQUAL TO '0'*/
/*TO GIVE OTHER VALUES TO THE VALUES IN THE LIST, USE {[NAME] = [VALUE], [NAME_TWO] = [VALUE_TWO],...} (FOR EXAMPLE: 'enum primary_color {red = "red", yellow = "yellow", blue = "blue"}*/
/*CHAR-TYPES CAN BE ANY SINGLE ALPHANUMERIC CHARACTER*/
/*REMEMBER FOR GIVING VALUES TO CHAR, USE SINGLE QUOTES (FOR EXAMPLE: 'char durk = 'T'')*/

/*FORMAT SPECIFIERS SPECIFY THE TYPE OF DATA, EXPRESSED BY A '%'*/
/*SPECIFIERS ARE: INT~%i, %d, FLOAT~%f, DOUBLE~%e, %g, CHAR~%c, BOOL~%i*/

/*COMMAND LINE ARGUMENTS PASSES DATA/VARIABLE TO A PROGRAM*/
/*FOR COMMAND LINE ARGUMENTS TO BE ABLE TO BE PASSED IN TO THE PROGRAM, ARGUMENTS MUST BE DECLARED IN 'main' (FOR EXAMPLE: 'main (int durk, char *murk)')*/
/*TWO ARGUMENTS ARE PASSED TO THE MAIN FUNCTION AT RUNTIME: THE NUMBER OF PASSED ARGUMENTS ('argc' FOR ARGUMENT COUNT) AND THE ARRAY CONTAINING THE ARGUMENTS ('argv' FOR ARGUMENT VECTOR)*/
/*THE FIRST ARGUMENT IS ALWAYS THE NAME OF THE FUNCTION (argv[0] IS THE NAME OF THE FUNCTION)*/

#include <stdio.h>
#include <stdbool.h>
#include <math.h>
#include <stdlib.h>
int main (int argc, char *argv[])
{
    bool durk = true;
    durk = 1;
    printf("DUUUUUURK %i\n", durk);

    enum color {red, blue, yellow}; 
    enum color murk = yellow;
    printf("DUUUUUUUUUUUUURK %i\n", murk);

    printf("DUUUUUUUUUUUUUURK %i\n", argc);
    printf("MURK %s\n", argv[1]);

    /*PASSING IN ARGUMENTS AND CONVERTING IT TO DOUBLE:*/
    double durkudurk = atoi(argv[1]);
    printf("SQUARE IS %e\n", (durkudurk*durkudurk));

    return 0;
}
