/*COMMENTS CAN BE DONE IN TWO WAYS:*/
// '/* ... */' FOR MULTILINE COMMENTS
// FOR ONE-LINE COMMENTS
/*IMPORTANT COMMENTS CAN BE EMPHASIZED WITH MORE ASTERISKS:*/
/*******************************************
 * COMMENTS
 *************************************/

/*PREPROCESSORS CAN BE IDENTIFIED WITH AN '#' AT THE VERY BEGINNING OF THE LINE*/
/*SOME OF THEM ARE : 'include', 'define' (MACROS), 'ifdef', 'endif', 'else', 'ifndef'*/
/*THESE ARE RUN BEFORE ANY CODE IS RUN AND ARE THEREFORE CALLED PREPROCESSORS*/
/*THE PREPROCESSOR 'include' CALLS EXTERNAL LIBRARIES (FOR EXAMPLE: '#include <stdio.h>')*/
/*PREPROCESSORS CAN BE ANYWHERE IN THE CODE, BUT ARE NORMALLY ALL AT THE BEGINNING*/
/*MOST OF THE TIME, HEADER-FILES ARE INCLUDED, WHICH HAVE AN '.h'-EXTENSION*/
/*THERE IS TWO WAYS TO INCLUDE A FILE, WITH '<>' AND WITH '""', WHICH MEAN, RESPECTIVELY, FILES IN A STANDARD SYSTEM DIRECTORY OR FILES IN CURRENT DIRECTORY (FOR EXAMPLE: '#include <stdio.h>' AND '#include "own_written_function.h"')*/
/*EXECUTABLE CODE NORMALLY DOES NOT GO INTO A HEADER FILE, BUT THAT GOES INTO A SOURCE CODE FILE*/

/*TO GET INPUT FROM USER: 'scanf()' IS THE MOST STANDARD ONE*/
/*TO READ IN EVERYTHING EXCEPT ARRAYS OR STRINGS, PRECEDE THE VARIABLE WITH '&' IN 'scanf'*/
/*THERE IS ONE DIFFERENCE BETWEEN THE CLASSIFIER AND THE OBJECT CALLED IN SCANF AND THAT IS IF THE VARIABLE IS A DOUBLE: 'double example' -> 'scanf("%lf", example)'*/

#include <stdio.h>

int main (void)
{
    char murk[10];
    int integer;
    printf("DUUUUUUUUUUUUUURK\n");
    scanf("%s %i", murk, &integer);
    printf("DUUUUUUUUUUUURK %s %i \n", murk, integer);
    return 0;
}
