# SUPERVISED LEARNING:
# LABELED DATA, MAKE A PREDICTION OF THE BEHAVIOUR/VALUE OF ONE OR MULTIPLE LABELS

# UNSUPERVISED LEARNING:
# UNLABELED DATA, TRY TO GROUP THEM TOGETHER AND/OR LABEL IT

# REINFORCEMENT LEARNING:
# TRY TO PERFORM AN ACTION BASED ON 'EXPERIENCE'. THROUGH TRIAL AND ERROR WHICH TACTICS OFFERS GREATEST BENEFITS. 
# THREE COMPONENTS: AGENT (THE ONE THAT TAKES ACTION), ENVIRONMENT (SURROUNDINGS) AND ACTIONS (SUSTAINED ACTIONS).