# MOST WIDELY USED ONES ARE CONTENT-BASED AND COLLABERATIVE FILTERING:
# CONTENT-BASED: RECOMMENDATIONS BASED ON SIMILAR FEATURES (FRIDGES AND FRIDGES)
# COLLABERATIVE FILTERING: RECOMMENDATIONS BASED ON COLLECTIVE BEHAVIOUR (A LOT OF PEOPLE BOUGHT THIS TOGETHER WITH THIS, YOU MIGHT AS WELL)
#     MEMORY-BASED: 
#     MODEL- BASED:

# TO CORRELATE THE ROWS WITHIN ON DATAFRAME USE .corr(), TO CORRELATE BETWEEN DIFFERENT DATAFRAMES USE .corrwith()