#  MACHINE LEARNING: DATA ANALYSIS THAT AUTOMATES MODEL-BUILDING/PARAMETER-SEARCHING
#      DEEP LEARNING: SUBFIELD OF MACHINE LEARNING WITH DEEP ARTIFICIAL NEURAL NETWORKS
#      SUPERVISED: LEARNING WITH LABELED DATA/PREDICTING CATEGORIES OR FEATURES
#      UNSUPERVISED: LEARNING WITH UNLABELED DATA/CLUSTERING DATA THAT IS NOT GROUPED (YET) AND/OR DIMENSIONALITY REDUCTION
#      EVALUATING: TRAIN-VALIDATION-TEST, WHERE VALIDATING IS TO IMPROVE PARAMETERS AND TESTING IS ON DIFFERENT SUBSET
#      UNDER-/OVERFITTING: BIAS-VARIANCE TRADE-OFF WHERE THE MORE/LESS BIAS MEANS A STRONGER/VARIABLE MODEL

#  EVALUATION METRICS:
#      REGRESSION:
#          L0 = ACCURACY = COUNTING HOW MANY ARE CORRECT (CORRECT IS STRETCHABLE, AS ALWAYS)
#          L1 = ABSOLUTE ERROR
#          L2 = (ROOT) MEAN SQUARED ERROR
#      CLASSIFICATION:
#          ACCURACY = RIGHT GUESSES / TOTAL; GOOD FOR BALANCED TARGET CLASS
#          PRECISION = CORRECT PREDICTED (TRUE) POSITIVES / PREDICTED POSITIVES
#          RECALL = CORRECT PREDICTED (TRUE) POSITIVES / ACTUAL POSITIVES
#          F1-SCORE = 2 * PRECISION * RECALL / ( PRECISION + RECALL ); HARMONIC MEAN
#  NOTE THAT FOR UNSUPERVISED LEARNING, THERE IS NO EVALUATION POSSIBLE
